# Generated by Django 2.0.13 on 2019-03-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=45000)),
                ('test_case1', models.CharField(max_length=1000)),
                ('test_case2', models.CharField(max_length=1000)),
                ('test_case3', models.CharField(max_length=1000)),
                ('test_case1_sol', models.CharField(max_length=1000)),
                ('test_case2_sol', models.CharField(max_length=1000)),
                ('test_case3_sol', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
