# Generated by Django 2.1.7 on 2019-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qno',
            field=models.IntegerField(default=0),
        ),
    ]
