# Generated by Django 2.0.13 on 2019-03-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_question_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='samplein',
            field=models.CharField(default='', max_length=45000),
        ),
        migrations.AddField(
            model_name='question',
            name='sampleout',
            field=models.CharField(default='', max_length=45000),
        ),
    ]
