# Generated by Django 2.0.13 on 2019-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190328_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='testcaseno',
            field=models.IntegerField(default=0),
        ),
    ]
