# Generated by Django 2.0.13 on 2019-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_question_testcaseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
