# Generated by Django 2.0.13 on 2019-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_question_correctanswered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAnswered',
        ),
        migrations.AddField(
            model_name='userdata',
            name='correctAnswered0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='correctAnswered1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='correctAnswered2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='correctAnswered3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='correctAnswered4',
            field=models.IntegerField(default=0),
        ),
    ]
