# Generated by Django 2.0.13 on 2019-03-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190329_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='correctAnswered0',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='correctAnswered1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='correctAnswered2',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='correctAnswered3',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='correctAnswered4',
        ),
        migrations.AddField(
            model_name='userdata',
            name='answer',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
