# Generated by Django 2.0.13 on 2019-03-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190329_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='answer',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
