# Generated by Django 2.0.13 on 2019-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190329_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='timeElapsed',
            field=models.IntegerField(default=0),
        ),
    ]
